CREATE TABLE alp_bms.USER_DETAILS (
	ACCOUNT_NUMBER BIGINT(16) PRIMARY KEY,
	ACCOUNT_TYPE VARCHAR(20) NOT NULL,
    ACCOUNT_HOLDER_NAME VARCHAR(20) NOT NULL,
    ACCOUNT_BALANCE DECIMAL(20,2)
);


CREATE TABLE alp_bms.TRANSACTION_DETAILS (
	TRANSACTION_ID BIGINT(20) PRIMARY KEY,
    ACCOUNT_NUMBER BIGINT(16),
    TRANSACTION_DESCRIPTION VARCHAR(30),
    TRANSACTION_TYPE VARCHAR(30),
	ACCOUNT_BALANCE DECIMAL(20,2),
    INDEX ACCOUNT_NUMBER_ID_INDEX(ACCOUNT_NUMBER),
	FOREIGN KEY(ACCOUNT_NUMBER) REFERENCES alp_bms.USER_DETAILS(ACCOUNT_NUMBER) ON DELETE CASCADE
);


INSERT INTO `alp_bms`.`USER_DETAILS`
(`ACCOUNT_NUMBER`,
`ACCOUNT_TYPE`,
`ACCOUNT_HOLDER_NAME`,
`ACCOUNT_BALANCE`)
VALUES
(1111222233334444,
'SAVING',
'shrikant kekane',
5000);

INSERT INTO `alp_bms`.`USER_DETAILS`
(`ACCOUNT_NUMBER`,
`ACCOUNT_TYPE`,
`ACCOUNT_HOLDER_NAME`,
`ACCOUNT_BALANCE`)
VALUES
(1111222233335555,
'SALARY',
'shrikant kekane',
0);
